# live reloading
watch:
  - documentation

# Project information
site_name: Red Aggregation
site_url: https://google.com
site_description: Bộ công cụ giúp chúng ta xây dựng, tái sử dụng và chia sẻ các pipeline MongoDB phức tạp một cách nhất quán
# Repository
repo_name: RedAggregation
# repo_url: https://github.com

# Copyright
copyright: ©Copyright <script>document.write(new Date().getFullYear())</script> - Red Aggregation Team</a>.

#Config
docs_dir: documentation/
google_analytics:
  - !!python/object/apply:os.getenv ["WORKFLOW_GOOGLE_ANALYTICS_KEY", "none"]
  - auto
use_directory_urls: false
plugins:
  - search:
    #        prebuild_index: true
      lang:
        - en
#For read the docs
# theme:
#     name: readthedocs
#     custom_dir: custom_theme/
#     highlightjs: true
#     sticky_navigation: false
# markdown_extensions:
#     - pymdownx.emoji:
#        emoji_index: !!python/name:pymdownx.emoji.twemoji
#        emoji_generator: !!python/name:pymdownx.emoji.to_alt
#     - toc:
#         permalink: true

#For material
theme:
  name: material
  custom_dir: custom_theme/
  features:
    - navigation.sections
    - navigation.expand
  favicon: assets/WebSite_Favicon.png
  # logo: "assets/OWASP_Logo.svg"
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences # Required by Pygments
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - toc:
      permalink: true
  - sane_lists